import "./PrivacyPolicy.scss";

export default function PrivacyPolicy() {
  return (
    <section className="policy-section">
      <div className="policy-container">
        <h3>Privacy Policy</h3>
        <p>Last updated: August 05, 2024</p>
        <p>
          This Privacy Policy describes our policies and procedures on the
          collection, use, and disclosure of your information when you use our
          Service and informs you about your privacy rights and how the law
          protects you.
        </p>
        <p>
          By using the Service, you agree to the collection and use of
          information in accordance with this Privacy Policy. This Privacy
          Policy has been created with the help of the Free Privacy Policy
          Generator.
        </p>

        <p>
          <strong>Interpretation and Definitions</strong>
        </p>

        <p>
          <strong>Interpretation</strong>
        </p>

        <p>
          The words with initial capital letters have meanings defined under the
          following conditions. These definitions shall have the same meaning
          regardless of whether they appear in singular or plural.
        </p>

        <p>
          <strong>Definitions</strong>
        </p>

        <p>For the purposes of this Privacy Policy:</p>

        <ul>
          <li>
            <span>
              <strong>Account:</strong>
            </span>{" "}
            A unique account created for you to access our Service or parts of
            our Service.
          </li>
          <li>
            <span>
              <strong>Affiliate:</strong>
            </span>{" "}
            An entity that controls, is controlled by, or is under common
            control with a party, where "control" means ownership of 50% or more
            of the shares, equity interest, or other securities entitled to vote
            for the election of directors or other managing authority.
          </li>
          <li>
            <span>
              <strong> Company </strong>
            </span>{" "}
            (referred to as either "the Company", "We", "Us" or "Our" in this
            Agreement) refers to tebtechnologyltd, 9 Thomas Adeboye Street,
            Olowora, Ojodu Berger, Lagos.
          </li>
          <li>
            <span>
              <strong>Cookies:</strong>
            </span>
            Small files placed on your computer, mobile device, or any other
            device by a website, containing details of your browsing history on
            that website among its many uses.
          </li>

          <li>
            <span>
              <strong>Country:</strong>
            </span>
            Nigeria
          </li>

          <li>
            <span>
              <strong>Device:</strong>
            </span>
            Any device that can access the Service such as a computer, a
            cellphone, or a digital tablet.
          </li>

          <li>
            <span>
              <strong>Personal Data:</strong>
            </span>
            Any information that relates to an identified or identifiable
            individual.
          </li>

          <li>
            <span>
              <strong>Service: </strong>
            </span>
            The Website.
          </li>

          <li>
            <span>
              <strong>Service Provider: </strong>
            </span>
            Any natural or legal person who processes the data on behalf of the
            Company. It refers to third-party companies or individuals employed
            by the Company to facilitate the Service, provide the Service on
            behalf of the Company, perform services related to the Service, or
            assist the Company in analyzing how the Service is used.
          </li>

          <li>
            <span>
              <strong>Usage Data: </strong>
            </span>
            Data collected automatically, either generated by the use of the
            Service or from the Service infrastructure itself (e.g., the
            duration of a page visit).
          </li>

          <li>
            <span>
              <strong>Website:</strong>
            </span>
            tebtechnologyltd, accessible from
            https://tebtechnologyltd-app.vercel.app
          </li>

          <li>
            <span>
              <strong>You:</strong>
            </span>
            The individual accessing or using the Service, or the company or
            other legal entity on behalf of which such individual is accessing
            or using the Service, as applicable.
          </li>
        </ul>

        <p>
          <strong>Collecting and Using Your Personal Data</strong>
        </p>

        <p>Types of Data Collected</p>

        <p>Personal Data</p>
        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul>
          <li>Email Address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
        </ul>

        <p>
          <strong>Tracking Technologies and Cookies</strong>
        </p>

        <p>
          We use Cookies and similar tracking technologies to track the activity
          on our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze our Service. The technologies we use may
          include:
        </p>

        <p>
          <strong>Cookies or Browser Cookies:</strong>A cookie is a small file
          placed on your Device. You can instruct your browser to refuse all
          cookies or to indicate when a cookie is being sent. However, if you do
          not accept cookies, you may not be able to use some parts of our
          Service. Unless you have adjusted your browser setting so that it will
          refuse cookies, our Service may use cookies.
        </p>

        <p>
          <strong>Web Beacons:</strong>
          Certain sections of our Service and our emails may contain small
          electronic files known as web beacons (also referred to as clear gifs,
          pixel tags, and single-pixel gifs) that permit the Company, for
          example, to count users who have visited those pages or opened an
          email and for other related website statistics (e.g., recording the
          popularity of a certain section and verifying system and server
          integrity).
        </p>

        <p>
          Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
          remain on your personal computer or mobile device when you go offline,
          while Session Cookies are deleted as soon as you close your web
          browser.
        </p>

        <p>
          We use both Session and Persistent Cookies for the purposes set out
          below:
        </p>

        <p>
          <strong>Necessary / Essential Cookies</strong>
          <ul>
            <li>Type: Session Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These Cookies are essential to provide you with services
              available through the Website and to enable you to use some of its
              features. They help authenticate users and prevent fraudulent use
              of user accounts. Without these Cookies, the services you have
              requested cannot be provided, and we only use these Cookies to
              provide you with those services.
            </li>
          </ul>
        </p>

        <p>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>
          <ul>
            <li>Type: Persistent Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These Cookies identify if users have accepted the use of
              cookies on the Website.
            </li>
          </ul>
        </p>

        <p>
          <strong>Functionality Cookies</strong>
          <ul>
            <li>Type: Persistent Cookies</li>
            <li>Administered by: Us</li>
            <li>
              Purpose: These Cookies allow us to remember choices you make when
              you use the Website, such as remembering your login details or
              language preference. The purpose of these Cookies is to provide
              you with a more personal experience and to avoid you having to
              re-enter your preferences every time you use the Website.
            </li>
          </ul>
        </p>

        <p>
          For more information about the cookies we use and your choices
          regarding cookies, please visit our Cookies Policy or the Cookies
          section of our Privacy Policy.
        </p>

        <p>
          <strong>Use of Your Personal Data</strong>
        </p>

        <p>The Company may use Personal Data for the following purposes:</p>

        <ul>
          <li>
            To provide and maintain our Service, including to monitor the usage
            of our Service.
          </li>
          <li>
            <strong>To manage your Account: </strong>To manage your registration
            as a user of the Service. The Personal Data you provide can give you
            access to different functionalities of the Service available to you
            as a registered user.
          </li>
          <li>
            <strong>For the performance of a contract: </strong>
            The development, compliance, and undertaking of the purchase
            contract for the products, items, or services you have purchased or
            any other contract with us through the Service.
          </li>
          <li>
            <strong>To contact you: </strong>
            To contact you by email, telephone calls, SMS, or other equivalent
            forms of electronic communication, such as a mobile application's
            push notifications regarding updates or informative communications
            related to the functionalities, products, or contracted services,
            including security updates, when necessary or reasonable for their
            implementation.
          </li>

          <li>
            <strong> To provide you with news, special offers, </strong>
            and general information about other goods, services, and events we
            offer that are similar to those you have already purchased or
            enquired about unless you have opted not to receive such
            information.
          </li>

          <li>
            <strong> To manage your requests: </strong>
            To attend and manage your requests to us.
          </li>

          <li>
            <strong> For business transfers: </strong>
            We may use your information to evaluate or conduct a merger,
            divestiture, restructuring, reorganization, dissolution, or other
            sale or transfer of some or all of our assets, whether as a going
            concern or as part of bankruptcy, liquidation, or similar
            proceeding, in which Personal Data held by us about our Service
            users is among the assets transferred.
          </li>

          <li>
            <strong> For other purposes: </strong>
            We may use your information for other purposes, such as data
            analysis, identifying usage trends, determining the effectiveness of
            our promotional campaigns, and evaluating and improving our Service,
            products, services, marketing, and your experience.
          </li>
        </ul>
        <p>
          <strong>Disclosure of Your Personal Data</strong>
        </p>
        <p>
          We may share your personal information in the following situations:
        </p>

        <ul>
          <li>
            <strong>With Service Providers:</strong>
            We may share your personal information with Service Providers to
            monitor and analyze the use of our Service, to contact you.
          </li>

          <li>
            <strong>For business transfers:</strong>
            We may share or transfer your personal information in connection
            with, or during negotiations of, any merger, sale of Company assets,
            financing, or acquisition of all or a portion of our business to
            another company.
          </li>

          <li>
            <strong>With Affiliates::</strong>
            We may share your information with our affiliates, in which case we
            will require those affiliates to honor this Privacy Policy.
            Affiliates include our parent company and any other subsidiaries,
            joint venture partners, or other companies that we control or that
            are under common control with us.
          </li>

          <li>
            <strong>With business partners:</strong>
            We may share your information with our business partners to offer
            you certain products, services, or promotions.
          </li>

          <li>
            <strong>With other users:</strong>
            When you share personal information or otherwise interact in public
            areas with other users, such information may be viewed by all users
            and may be publicly distributed outside.
          </li>

          <li>
            <strong>With your consent:</strong>
            We may disclose your personal information for any other purpose with
            your consent.
          </li>
        </ul>

        <p>
          <strong>Retention of Your Personal Data</strong>
        </p>

        <p>
          The Company will retain your Personal Data only for as long as
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations (e.g., if we are required to retain your
          data to comply with applicable laws), resolve disputes, and enforce
          our legal agreements and policies.
        </p>
      </div>
    </section>
  );
}
